#!/usr/bin/env python

import sys
import os
import string

def main():
  fn = sys.argv[1]
  revs = map(string.strip,os.popen('git-rev-list HEAD -- %s'%fn).readlines())
  #revs.append(revs[-1]+'^')
  revs.insert(0,'HEAD')
  
  for i in range(len(revs)-1):
    os.system('git-diff %s %s %s'%(revs[i+1],revs[i],fn))
  
  print revs
  
if __name__=='__main__':
  main()
